# Generated by Django 4.1.4 on 2023-02-01 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_follower_follows_alter_follower_owner'),
        ('feed', '0003_comment_bosse'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='value',
            field=models.CharField(choices=[('up', 'Up vote'), ('down', 'Down vote')], default='down', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('owner', 'post')},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='bosse',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='short_troll',
        ),
    ]
