# Generated by Django 4.1.4 on 2023-01-16 16:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_follower_follows_alter_follower_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaPost',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('post_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('votes', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
