# Generated by Django 4.1.4 on 2023-01-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mangapost',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='mangapost',
            old_name='votes',
            new_name='total_downvotes',
        ),
        migrations.AddField(
            model_name='mangapost',
            name='total_upvotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
