# Generated by Django 4.1.4 on 2023-02-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0005_mangapost_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mangacomment',
            options={'ordering': ['-created']},
        ),
    ]
